scroller_structs=20
scroller_default_proportion=1
scroller_focus_center=1
scroller_prefer_center=0
edge_scroller_pointer_focus=1

scroller_default_proportion_single=1.0
scroller_proportion_preset=0.5,0.8,1.0

new_is_master=1
default_mfact=0.55
default_nmaster=1
smartgaps=0

repeat_rate=25
repeat_delay=600
numlockon=0
xkb_rules_layout=us, ru
xkb_rules_options=grp:alt_shift_toggle

disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=1
disable_while_typing=1
left_handed=0
middle_button_emulation=0
swipe_min_threshold=1

mouse_natural_scrolling=0

cursor_size=24

gappih=5
gappiv=5
gappoh=10
gappov=10

hotarea_size=10
enable_hotarea=1

ov_tab_mode=0
overviewgappi=5
overviewgappo=30

scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9

enable_floating_snap=0
snap_distance=30

drag_tile_to_tile=12