# Яндекс Музыка
bind=SUPER,m,toggle_named_scratchpad,yandex-music,none,yandex-music
windowrule=isnamedscratchpad:1,appid:yandex-music

# AyuGram — имя scratchpad должно совпадать с appid
# bind=SUPER,d,toggle_named_scratchpad,com.ayugram.desktop,none,AyuGram
# windowrule=isnamedscratchpad:1,appid:com.ayugram.desktop


bind=SUPER,d,toggle_named_scratchpad,io.github.kukuruzka165.materialgram,none,flatpak run io.github.kukuruzka165.materialgram  
windowrule=isnamedscratchpad:1,appid:io.github.kukuruzka165.materialgram

bind=SUPER,s,toggle_named_scratchpad,Happ,none,happ
windowrule=isnamedscratchpad:1,appid:Happ

bind=SUPER,l,toggle_named_scratchpad,localsend,none,flatpak run org.localsend.localsend_app
windowrule=isnamedscratchpad:1,appid:localsend

scratchpad_width_ratio=1.0
scratchpad_height_ratio=1.0