# Яндекс Музыка
bind=SUPER,m,toggle_named_scratchpad,YandexMusic,none,/opt/yandex-music/yandexmusic
windowrule=isnamedscratchpad:1,appid:YandexMusic

# AyuGram — имя scratchpad должно совпадать с appid
bind=SUPER,d,toggle_named_scratchpad,com.ayugram.desktop,none,AyuGram
windowrule=isnamedscratchpad:1,appid:com.ayugram.desktop

# Hiddify
bind=SUPER,s,toggle_named_scratchpad,app.hiddify.com,none,vpn_start
windowrule=isnamedscratchpad:1,appid:app.hiddify.com