exec = hyprctl dispatch submap global
submap = global

# Files
source=conf/monitors.conf
source=conf/variables.conf
source=conf/general.conf
source=conf/execs.conf
source=conf/keybinds.conf
source=conf/special_workspace.conf
source=conf/rules.conf

source = /home/sammy/.config/hypr/noctalia/noctalia-colors.conf