exec = hyprctl dispatch submap global
submap = global

# Files
source=./monitors.conf
source=./variables.conf
source=./general.conf
source=./execs.conf
source=./keybinds.conf
source=./special_workspace.conf