#!/bin/sh

get_app_config() {
    case "$1" in
        music)
            printf 'YandexMusic|/opt/yandex-music/yandexmusic'
            ;;
        telegram)
            printf 'com.ayugram.desktop|AyuGram\n'
            ;;
        vpn)
            printf 'app.hiddify.com|vpn_start\n'
            ;;
        obsidian)
            printf 'obsidian|obsidian\n'
            ;;
        *)
            printf 'unknown|\n'
            ;;
    esac
}

config=$(get_app_config "$1")
app_class="${config%|*}"
app_command="${config#*|}"
if hyprctl clients -j | jq -e ".[] | select(.class == \"$app_class\")" >/dev/null 2>&1; then
    echo "$1 уже запущено"
else
    echo "Запускаем $1..."
    echo $app_command
    $app_command >/dev/null 2>&1 &
fi
hyprctl dispatch togglespecialworkspace "$1"
echo "$1"
