source=./cfg/windows.conf
source=./cfg/binds.conf
source=./cfg/animations.conf
source=./cfg/rules.conf
source=./cfg/general.conf
source=./cfg/execs.conf
source=./cfg/special_workspaces.conf
# This sources the noctalia theme

source = /home/sammy/.config/mango/noctalia.conf