# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x291414ff
rootcolor = 0x291414ff
bordercolor = 0x756161ff
focuscolor = 0xe86463ff
maximizescreencolor = 0xe59a4dff
urgentcolor = 0x8a1514ff
scratchpadcolor = 0xe4e54dff
globalcolor = 0x900908ff
overlaycolor = 0x794107ff
