# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x281519ff
rootcolor = 0x281519ff
bordercolor = 0x756165ff
focuscolor = 0xe46780ff
maximizescreencolor = 0x5c89d6ff
urgentcolor = 0xfd4663ff
scratchpadcolor = 0xccb866ff
globalcolor = 0x8d0c25ff
overlaycolor = 0x10336fff
