# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x0c0d31ff
rootcolor = 0x0c0d31ff
bordercolor = 0x5e5f72ff
focuscolor = 0x9094ebff
maximizescreencolor = 0xba95e6ff
urgentcolor = 0xfd4663ff
scratchpadcolor = 0xe295e6ff
globalcolor = 0x1017b9ff
overlaycolor = 0x5e17b1ff
