windowrule = match:class ^app.hiddify.com$, workspace special:vpn
windowrule = match:class ^YandexMusic$, workspace special:music
windowrule = match:class ^com.ayugram.desktop$, workspace special:telegram
