alias c="clear"
alias ls="exa"
alias aliascf="nano ~/.config/fish/alias.fish"
alias hs="history | grep --color=auto "
alias dc="docker compose"
alias almrev="alembic revision --autogenerate -m"
alias almup="alembic upgrade head"
alias flutter_build="flutter pub run build_runner build --delete-conflicting-outputs"
alias dcdev="docker compose -f docker-compose.dev.yml"
alias sshp="ssh -p 1009 sammy@lednevs.ru"
