-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("SUPER + O")
hl.bind("SUPER + O", hl.dsp.exec_cmd("dms ipc call dankdash wallpaper"), { description = "Wallpaper Browser" })
hl.unbind("SUPER + R")
hl.bind("SUPER + R", hl.dsp.exec_cmd("dms ipc call spotlight toggle"), { description = "dms ipc call spotlight toggle" })
hl.unbind("SUPER + SHIFT + right")
hl.bind("SUPER + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.unbind("SUPER + SHIFT + up")
hl.bind("SUPER + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.unbind("SUPER + code:20")
hl.bind("SUPER + code:20", hl.dsp.window.resize({ x = -100, y = 0, relative = true }), { description = "Expand window left" })
hl.unbind("SUPER + code:21")
hl.bind("SUPER + code:21", hl.dsp.window.resize({ x = 100, y = 0, relative = true }), { description = "Shrink window left" })
hl.unbind("SUPER + down")
hl.bind("SUPER + down", hl.dsp.focus({ direction = "d" }))
hl.unbind("SUPER + equal")
hl.bind("SUPER + equal", hl.dsp.window.resize({ x = 100, y = 0, relative = true }), { repeating = true })
hl.unbind("SUPER + left")
hl.bind("SUPER + left", hl.dsp.focus({ direction = "l" }))
hl.unbind("SUPER + minus")
hl.bind("SUPER + minus", hl.dsp.window.resize({ x = -100, y = 0, relative = true }), { repeating = true })
hl.unbind("SUPER + mouse:272")
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { description = "Move window" })
hl.unbind("SUPER + mouse:273")
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { description = "Resize window" })
hl.unbind("SUPER + right")
hl.bind("SUPER + right", hl.dsp.focus({ direction = "r" }))
hl.unbind("SUPER + up")
hl.bind("SUPER + up", hl.dsp.focus({ direction = "u" }))
hl.unbind("SUPER + B")
hl.bind("SUPER + B", hl.dsp.exec_cmd("zen-browser"))
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("foot"), { description = "ghostty" })
hl.unbind("SUPER + T")
hl.bind("SUPER + T", hl.dsp.exec_cmd("foot"), { description = "foot" })
hl.unbind("SUPER + SHIFT + E")
hl.bind("SUPER + SHIFT + E", hl.dsp.exit())
hl.unbind("SUPER + SHIFT + P")
hl.bind("SUPER + SHIFT + P", hl.dsp.dpms({ action = "toggle" }))
hl.unbind("SUPER + CTRL + F")
hl.bind("SUPER + CTRL + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.unbind("SUPER + SHIFT + F")
hl.bind("SUPER + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.unbind("SUPER + SHIFT + T")
hl.bind("SUPER + SHIFT + T", hl.dsp.window.float({ action = "toggle" }))
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.group.toggle())
hl.unbind("SUPER + bracketleft")
hl.bind("SUPER + bracketleft", hl.dsp.layout("preselect l"))
hl.unbind("SUPER + bracketright")
hl.bind("SUPER + bracketright", hl.dsp.layout("preselect r"))
hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("happ"))
hl.bind("SUPER + D", hl.dsp.workspace.toggle_special("tg"))
hl.unbind("SUPER + M")
hl.bind("SUPER + M", hl.dsp.workspace.toggle_special("music"))
