-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(bdc2ff)",
			inactive_border = "rgb(91909a)",
		},
	},
	group = {
		col = {
			border_active = "rgb(bdc2ff)",
			border_inactive = "rgb(91909a)",
			border_locked_active = "rgb(ffb4ab)",
			border_locked_inactive = "rgb(91909a)",
		},
		groupbar = {
			col = {
				active = "rgb(bdc2ff)",
				inactive = "rgb(91909a)",
				locked_active = "rgb(ffb4ab)",
				locked_inactive = "rgb(91909a)",
			},
		},
	},
})
