##! Apps
bind = Super, T, exec, foot # terminal
bind = Super, Return, exec, foot # terminal
bind = Super, B, exec, firefox # browser
bind = Super, R, exec, fuzzel --show # app launcher
bind = Super SHIFT, T, exec, quickshell -c QuickSnip -n # scan text
bind = Super SHIFT, R, exec, quickshell -c HyprQuickFrame -n # screenshot
bind = Super, E, exec, cosmic-files

##! Window Management
bind = Super, Q, killactive # close window
bind = Super, F, fullscreen, 0 # fullscreen
binde = Super, semicolon, resizeactive, -50 0 # resizeactive <=
binde = Super, apostrophe, resizeactive, 50 0 # resizeactive =>

##! Media
bind = , KP_Add, exec, playerctl play-pause # play-pause
bind = , KP_Subtract, exec, playerctl next # next track
bind = , KP_Multiply, exec, playerctl previous # previous track

bind = ,XF86AudioRaiseVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = ,XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = ,XF86AudioMute,exec,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bind = Super+Shift+Alt, mouse:275, exec, playerctl previous
bind = Super+Shift+Alt, mouse:276, exec, playerctl next || playerctl position `bc <<< "100 * $(playerctl metadata mpris:length) / 1000000 / 100"`


##! light
bind = , XF86MonBrightnessUp, exec, brightnessctl set +10% # Увеличить яркость на 10%
bind = , XF86MonBrightnessDown, exec, brightnessctl set 10%- # Уменьшить яркость на 10%


##! Wallpaper
bind = Super, W, exec, qs ipc call wallpaper-picker toggle

##! Workspaces
bind = Super, 1, workspace, 1
bind = Super, 2, workspace, 2
bind = Super, 3, workspace, 3
bind = Super, 4, workspace, 4
bind = Super, 5, workspace, 5
bind = Super, 6, workspace, 6
bind = Super, 7, workspace, 7
bind = Super, 8, workspace, 8
bind = Super, 9, workspace, 9
bind = Super, 0, workspace, 10

bind = Super SHIFT, 1, movetoworkspace, 1
bind = Super SHIFT, 2, movetoworkspace, 2
bind = Super SHIFT, 3, movetoworkspace, 3
bind = Super SHIFT, 4, movetoworkspace, 4
bind = Super SHIFT, 5, movetoworkspace, 5
bind = Super SHIFT, 6, movetoworkspace, 6
bind = Super SHIFT, 7, movetoworkspace, 7
bind = Super SHIFT, 8, movetoworkspace, 8
bind = Super SHIFT, 9, movetoworkspace, 9
bind = Super SHIFT, 0, movetoworkspace, 10