bind = Super, S, exec, ~/.config/hypr/scripts/workspaces vpn
bind = Super, D, exec, ~/.config/hypr/scripts/workspaces telegram
bind = Super, M, exec, ~/.config/hypr/scripts/workspaces music
#bind = Super, I, exec, ~/.config/hypr/scripts/workspaces obsidian

windowrule = match:class ^app.hiddify.com$, workspace special:vpn
windowrule = match:class ^YandexMusic$, workspace special:music
windowrule = match:class ^com.ayugram.desktop$, workspace special:telegram
#windowrule = match:class ^obsidian$, workspace special:obsidian
